### ISSUE TITLE
Settle on keybindings

### ISSUE THREAD

**Issue by JorisE** [JorisE/evil-mu4e#1]
The mu4e keybindings are well known by its users, so changing to much may make it harder to use than nessecary For now, only changes that are necessary to work with mu4e with evil-mode enabled are in evil-mu4e.
If anyone has ideas on other keybindings that make sense, I'd be happy to hear them.

**Comment by JorisE** [comment]
On the issue of `j` vs `J` for jumping to maildir. My preference goes toward using `J` so that `j` is free for the movement we know and love from VIM.

When on a bookmark (or maildir, if you use maildir-extension), hitting enter will bring you to the expected location. 

For me personally, I rarely if ever use the concept of maildirs since I use mu4e, so having the `jump-to-maildir` under a key without having to press `<shift>` is not really an issue for me.

**Comment by jojojames** [comment]
How about (mu4e-headers-mark-for-flag) -> +?

http://www.djcbsoftware.nl/code/mu/mu4e/What-to-mark-for.html

Think it's the default.

**Comment by JorisE** [comment]
@jojojames: Don't know where that went really. That could be added.

**Comment by jojojames** [comment]
Sounds great.

**Comment by liujoey** [comment]
How about this action:

```
g            go to (visit) numbered URL (using `browse-url')
(or: <mouse-1> or M-RET with point on url)
```

**Comment by JorisE** [comment]
@liujoey mouse-1 works for me. Isn't that an Emacs default? The g would be helpful. Is that the mu4e default?

**Comment by liujoey** [comment]
I found `g` in mu4e INFO page. So I assume it's the default. But now it was bound to `gg` by evil.

**Comment by JorisE** [comment]
I imagine that `gg` makes sense to have in view mode. Do you have an idea for a sensible keybinding?

**Comment by japhir** [comment]
I think `gg` is less important in emails, if people are sending you emails long enough that you require jumping to the top I would have a serious word with them ;-).

I just noticed that `g1` wasn't working to go to an URL and neither was hitting RET when the cursor was over it. I would be for overriding gg in favour of g, but maybe another keybinding could work as well.
What about gu for "go to url"?

**Comment by jtmoulia** [comment]
I like @japhir's idea of keeping `gg`'s evil keybinding (I do use it) and using `gu` for "go to url". In general, if evil conflicts with mu4e in view-mode, my preference is always to go with the evil keybinding and rebind the mu4e keybinding to some mnemonic like `gu`. My muscle memory is evil.

**Comment by Ambrevar** [comment]
I think most of this is fixed by now.

**Comment by Ambrevar** [comment]
Please see https://github.com/emacs-evil/evil-collection from now on.
