### ISSUE TITLE
Support deactivating VIM keybindings

### ISSUE THREAD

**Issue by JorisE** [JorisE/evil-mu4e#11]
To be included in Spacemacs, evil-mu4e has to support deactivating the keybindings. That way a user can choose to use Emacs keybindings.

See: https://github.com/syl20bnr/spacemacs/pull/5114

**Comment by Ambrevar** [comment]
What's the difference between that and `M-x evil-emacs-state`?

**Comment by Ambrevar** [comment]
Please see https://github.com/emacs-evil/evil-collection from now on.
