### ISSUE TITLE
Binding "Mark Pattern" to '%'

### ISSUE THREAD

**Issue by nighthawk9** [JorisE/evil-mu4e#12]
Making this a default for evil-mu4e would follow the consistency brought by evil-collection.

Would it be possible to add it the evil-mu4e officially?

**Comment by JorisE** [comment]
Sure, just send a PR.

**Comment by Ambrevar** [comment]
This can be closed now, right?

**Comment by nighthawk9** [comment]
Yes it can. My apologies. It's now closed.
