### ISSUE TITLE
evil-get-auxiliary-keymap: Wrong type argument: keymapp, mu4e-main-mode-map

### ISSUE THREAD

**Issue by Nathoufresh** [JorisE/evil-mu4e#19]
I get
`evil-get-auxiliary-keymap: Wrong type argument: keymapp, mu4e-main-mode-map` when trying to launch it using emacs 27.

**Comment by JorisE** [comment]
Hi @Nathoufresh, this repo exists only for historical purposes. evil-mu4e has been merged into https://github.com/emacs-evil/evil-collection

**Comment by Nathoufresh** [comment]
Sorry I didn't notice, thanks for your input!
