### ISSUE TITLE
Typo in new keybindings?

### ISSUE THREAD

**Issue by moesasji** [JorisE/evil-mu4e#2]
I'm trying out evil-mu4e to understand how to get mu4e to work better with evil-mode. In doing so I spotted a couple of issues, besides the question what keybindings to use:

1) In the function evil-mu4e-new-region-basic the shortcut to compose is given as a lowercase c. This is a capital C, so looks like a typo.

2) Same type of typo applies to the help command in the function evil-mu4e-new-region-misc. There the shortcut is given as a lowercase h, which is a movement command. However a capital H jumps to the beginning of the file. So it looks like it is both a typo and you need to rebind the shortcut for the help. To me it seems that the default H used in mu4e would be suitable as 'gg' does the same anyway.

3) If I go to the about screen or the news screen the keybinding 'q' to close them doesn't work. Adding mu4e-org-mode to the modes that get set to the evil-mu4e-state-mode fixes this for me.

*) In the message-view mode normally there is 'y' to jump to the displayed headers. This gets overridden by yank, so would need a different key-binding....looking at the keybindings in the mu4e manual there will be many more to do, but you already have an issue open for that.

edit) note that the last comment also implies that there are a lot of mu4e keybindings that don't work in things like the message-view. This happens because you use motion state instead of emacs-state, which intentional, but overwrites a lot of bindings. Anyway, it might be good to make this clearer in the readme?

edit2) The longer I think about the less sense it makes to start from the motion state. You can see here how many keys that are used by mu4e get bound in that state: https://github.com/cjohansen/.emacs.d/blob/master/site-lisp/evil/evil-maps.el in that state.

**Comment by JorisE** [comment]
Thanks for noticing! I can fix the typo's shortly.

On the keybindings. You are right that there are currently a lot of unbound keys. The setup works really well for me, but there are indeed keys that are not covered. Pull Requests are more than welcome.

Do I understand correctly that you propose using Emacs state altogether? That would seem to me to make things more confusing. Being that this package is called `evil`-mu4e, I really intended it to have as little surprises as possible for people that use evil. :)

**Comment by JorisE** [comment]
The issues have been resolved, keeping this open for a while. I'd be happy to hear any suggested mode from @moesasji .

Maybe an overriding keymap (https://github.com/syl20bnr/spacemacs/wiki/Keymaps-guide) for the few bindings that should change, would be an idea.

**Comment by moesasji** [comment]
Sorry for the slow response; I can't help in terms of key-bindings as despite using evil I find it less confusing to use mu4e with its default key-bindings as they are pretty extensive and depend on the view that is open. Being able to look them up in the manual for the corresponding mode (using 'H') is more useful to me.

So the answer is indeed that at the moment I'm using mu4e in emacs-state instead of motion-state but fully agree that this isn't ideal either. All I was saying is that emacs-state might be a better starting point as that way you could just add only add basic vim-bindings such as motions and you don't have to redefine that many of the mu4e keys.

btw) I just reviewed your code to figure out a problem I had with using mu4e directly that wasn't there with evil-mu4e. Anyway keep up the good work!

**Comment by JorisE** [comment]
No problem. I'll just close this ticket than.
