### ISSUE TITLE
`h` ( move left ) doesn't -- in mu4e-view mode

### ISSUE THREAD

**Issue by naclander** [JorisE/evil-mu4e#5]
When reading an email in mu4e-view mode, it seems hitting `h` toggles html on the message, if available. Since `hjkl` are movement keys in evil, I think this package should overwrite this key binding to another key.

Thanks for the great work on these bindings so far.

**Comment by JorisE** [comment]
That makes sense. Do you have a suggestion for an alternative key-binding?

**Comment by naclander** [comment]
H seems like it would fit better no? And I beleive it is currently unbounded. What do you ( or anyone else ) think?

**Comment by JorisE** [comment]
@naclander thanks for fixing this!
